import java.awt.*;
import javax.swing.*;

public class AddClassScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddClassScreen
     */
    public AddClassScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tempBypassButton = new javax.swing.JButton();
        centerButton = new javax.swing.JButton();
        surround1 = new javax.swing.JButton();
        surround2 = new javax.swing.JButton();
        surround3 = new javax.swing.JButton();
        surround4 = new javax.swing.JButton();
        surround5 = new javax.swing.JButton();
        surround6 = new javax.swing.JButton();
        surroundField1 = new javax.swing.JTextField();
        surroundField2 = new javax.swing.JTextField();
        surroundField3 = new javax.swing.JTextField();
        surroundField4 = new javax.swing.JTextField();
        surroundField5 = new javax.swing.JTextField();
        surroundField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 128));

        tempBypassButton.setText("Temporary Bypass");
        tempBypassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempBypassButtonActionPerformed(evt);
            }
        });

        centerButton.setText("ADD PROGRAM");
        centerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerButtonActionPerformed(evt);
            }
        });

        surround1.setText("jButton2");
        surround1.setVisible(false);
        surround1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surround1ActionPerformed(evt);
            }
        });

        surround2.setVisible(false);
        surround2.setText("jButton3");
        surround2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surround2ActionPerformed(evt);
            }
        });

        surround3.setVisible(false);
        surround3.setText("jButton4");

        surround4.setVisible(false);
        surround4.setText("jButton5");

        surround5.setVisible(false);
        surround5.setText("jButton6");

        surround6.setVisible(false);
        surround6.setText("jButton7");

        surroundField1.setText("ADD COURSE");
        surroundField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surroundField1ActionPerformed(evt);
            }
        });

        surroundField2.setText("ADD COURSE");
        surroundField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surroundField2ActionPerformed(evt);
            }
        });

        surroundField3.setText("ADD COURSE");
        surroundField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surroundField3ActionPerformed(evt);
            }
        });

        surroundField4.setText("ADD COURSE");
        surroundField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surroundField4ActionPerformed(evt);
            }
        });

        surroundField5.setText("ADD COURSE");
        surroundField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surroundField5ActionPerformed(evt);
            }
        });

        surroundField6.setText("ADD COURSE");
        surroundField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surroundField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(surroundField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surround5)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(surround6)
                        .addComponent(surroundField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(surround1)
                                        .addComponent(surroundField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(surround4)
                                            .addComponent(centerButton)
                                            .addComponent(surroundField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surround3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(surroundField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(133, 133, 133))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(336, 336, 336)
                                .addComponent(tempBypassButton)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(surroundField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(surround2))
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(surround1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surroundField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surround6)
                    .addComponent(surround2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surroundField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(surroundField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(surround5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(surroundField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(centerButton)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(surround3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(surroundField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(surround4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addComponent(surroundField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(tempBypassButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tempBypassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempBypassButtonActionPerformed
        MainScreen screen = new MainScreen();
        screen.setVisible(true);
        screen.toFront();
    }//GEN-LAST:event_tempBypassButtonActionPerformed

    private void centerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerButtonActionPerformed
        final int mandatoryNum = 3;
        String[] mandatoryCourses = {"SPH4U", "SCH4U", "ENG4U"};
        JButton[] courses = {surround1, surround2, surround3, surround4, surround5, surround6};
        JTextField[] fillIn = {surroundField1, surroundField2, surroundField3, surroundField4, surroundField5, surroundField6};
        for(int i = 0; i < mandatoryNum; i++){
            courses[i].setVisible(true);
            fillIn[i].setVisible(false);
            courses[i].setText(mandatoryCourses[i]);
        }
        
    }//GEN-LAST:event_centerButtonActionPerformed

    private void surround1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surround1ActionPerformed
        
    }//GEN-LAST:event_surround1ActionPerformed

    private void surround2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surround2ActionPerformed

    }//GEN-LAST:event_surround2ActionPerformed

    private void surroundField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surroundField2ActionPerformed
        String input = surroundField2.getText();
        surroundField2.setVisible(false);
        surround2.setText(input);
        surround2.setVisible(true);
    }//GEN-LAST:event_surroundField2ActionPerformed

    private void surroundField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surroundField1ActionPerformed
        String input = surroundField1.getText();
        surroundField1.setVisible(false);
        surround1.setText(input);
        surround1.setVisible(true);
    }//GEN-LAST:event_surroundField1ActionPerformed

    private void surroundField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surroundField3ActionPerformed
        String input = surroundField3.getText();
        surroundField3.setVisible(false);
        surround3.setText(input);
        surround3.setVisible(true);
    }//GEN-LAST:event_surroundField3ActionPerformed

    private void surroundField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surroundField4ActionPerformed
        String input = surroundField4.getText();
        surroundField4.setVisible(false);
        surround4.setText(input);
        surround4.setVisible(true);
    }//GEN-LAST:event_surroundField4ActionPerformed

    private void surroundField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surroundField6ActionPerformed
        String input = surroundField6.getText();
        surroundField6.setVisible(false);
        surround6.setText(input);
        surround6.setVisible(true);
    }//GEN-LAST:event_surroundField6ActionPerformed

    private void surroundField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surroundField5ActionPerformed
        String input = surroundField5.getText();
        surroundField5.setVisible(false);
        surround5.setText(input);
        surround5.setVisible(true);
    }//GEN-LAST:event_surroundField5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClassScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton centerButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton surround1;
    private javax.swing.JButton surround2;
    private javax.swing.JButton surround3;
    private javax.swing.JButton surround4;
    private javax.swing.JButton surround5;
    private javax.swing.JButton surround6;
    private javax.swing.JTextField surroundField1;
    private javax.swing.JTextField surroundField2;
    private javax.swing.JTextField surroundField3;
    private javax.swing.JTextField surroundField4;
    private javax.swing.JTextField surroundField5;
    private javax.swing.JTextField surroundField6;
    private javax.swing.JButton tempBypassButton;
    // End of variables declaration//GEN-END:variables
}
