import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.*;

public class AddClassScreen extends javax.swing.JFrame {
    public static ArrayList<String> mandatoryCourses = new ArrayList();
    public static HashMap<JComboBox, String> chosenCourses = new HashMap<>();
    public static String programName = null;
    public static JLabel[] labels;
    public static JComboBox[] courses;
//    private boolean isSelectionMade = false;
//    private int choicesNum = 0;
    

    public AddClassScreen(){
        initComponents();
        uniInfo.putty();
        for (String i: uniInfo.universities){
            uniDropDown.addItem(i);
        }
        for (String i: uniInfo.ottawa){
            programDropDown.addItem(i);
        }
        courses = new JComboBox[]{courses1, courses2, courses3, courses4, courses5, courses6};
        labels = new JLabel[]{jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6};
        for (int i = 0; i < courses.length; i++ ){
            for (String j : uniInfo.HSCourses){
                courses[i].addItem(j);
            }
        }
//        nextButton.setEnabled(false);
    }
    
    public void choiceTrack() {
    String university = String.valueOf(uniDropDown.getSelectedItem());
    String program = String.valueOf(programDropDown.getSelectedItem());
    switch (university) {
        case "uOttawa":
            switch (program) {
                case uniInfo.PROG_NAME_01:
                    programName = uniInfo.PROG_NAME_01;
                    mandatoryCourses.clear();
                    for (String course : uniInfo.uMandatoryCourses.get(program)) {
                        mandatoryCourses.add(course);
                    }
                    System.out.println("Mandatory Courses for uOttawa Program 01: " + mandatoryCourses);
                    for (int j = 0; j < labels.length && j < mandatoryCourses.size(); j++) {
                        labels[j].setVisible(true);
                        labels[j].setText(mandatoryCourses.get(j));
                    }
                    break;
                case uniInfo.PROG_NAME_02:
                    
                    break;
                case uniInfo.PROG_NAME_03:
                    
                    break;
                default:
                    System.out.println("Error: Invalid program selected for uOttawa.");
            }
            break;
        case "uToronto":
            switch (String.valueOf(programDropDown.getSelectedItem())) {
                case uniInfo.PROG_NAME_01:
                    
                    break;
                case uniInfo.PROG_NAME_02:
                    
                    break;
                case uniInfo.PROG_NAME_03:
                    
                    break;
                default:
                    System.out.println("Error: Invalid program selected for uToronto.");
            }
            break;
        default:
            System.out.println("Error: Invalid university selected.");
    }
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        programDropDown = new javax.swing.JComboBox<>();
        uniDropDown = new javax.swing.JComboBox<>();
        courses1 = new javax.swing.JComboBox<>();
        courses2 = new javax.swing.JComboBox<>();
        courses3 = new javax.swing.JComboBox<>();
        courses4 = new javax.swing.JComboBox<>();
        courses5 = new javax.swing.JComboBox<>();
        courses6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddFirstClassButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 128));

        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        programDropDown.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                programDropDownMouseMoved(evt);
            }
        });
        programDropDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                programDropDownMouseClicked(evt);
            }
        });
        programDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programDropDownActionPerformed(evt);
            }
        });

        uniDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniDropDownActionPerformed(evt);
            }
        });

        courses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses1ActionPerformed(evt);
            }
        });

        courses2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses2ActionPerformed(evt);
            }
        });

        courses3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses3ActionPerformed(evt);
            }
        });

        courses4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses4ActionPerformed(evt);
            }
        });

        courses5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses5ActionPerformed(evt);
            }
        });

        courses6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses6ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AddFirstClassButton.setText("Add First Class");
        AddFirstClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFirstClassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(courses5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(courses3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(163, Short.MAX_VALUE)
                        .addComponent(courses6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(AddFirstClassButton))
                    .addComponent(programDropDown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uniDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(346, 346, 346))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(courses4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(courses1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(courses2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddFirstClassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courses1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(courses2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(programDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(courses6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(uniDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(courses3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(courses5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(courses4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(nextButton)
                .addContainerGap())
        );

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
//        if (chosenCourses.size() < 6) {
//        nextButton.setText("ENTER AT LEAST 6 COURSES");
//        return;
//        }
//    
//        if (!mandatoryCourses.isEmpty() && !chosenCourses.keySet().containsAll(mandatoryCourses)) {
//        nextButton.setText("SELECT ALL MANDATORY COURSES");
//        return;
//        }
//        System.out.print(chosenCourses);
//        if (!mandatoryCourses.isEmpty() && chosenCourses.keySet().containsAll(mandatoryCourses)) {
//        MainScreen screen = new MainScreen();
//        screen.setVisible(true);
//        screen.toFront();
//        dispose();
//        } 
//        else if (chosenCourses.size() < 6) {
//        nextButton.setText("ENTER AT LEAST 6 COURSES");
//        } 
//        else {
//        nextButton.setText("ENTER MANDATORY COURSES");
//        } 
//        
    System.out.print(chosenCourses.values());
            if (chosenCourses.size() < 6) {
        nextButton.setText("ENTER AT LEAST 6 COURSES");
        return;
    }

    if (!mandatoryCourses.isEmpty()) {
        boolean allMandatorySelected = true;
        for (String course : mandatoryCourses) {
            boolean found = false;
            for (String selectedCourse : chosenCourses.values()) {
                if (selectedCourse.equals(course)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                allMandatorySelected = false;
                break;
            }
        }
        if (!allMandatorySelected) {
            nextButton.setText("SELECT ALL MANDATORY COURSES");
            return;
        }
    }

    // Proceed to the next step
    MainScreen screen = new MainScreen();
    screen.setVisible(true);
    screen.toFront();
    dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void programDropDownMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programDropDownMouseMoved
      
    }//GEN-LAST:event_programDropDownMouseMoved

    private void programDropDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programDropDownMouseClicked

    }//GEN-LAST:event_programDropDownMouseClicked

    private void programDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programDropDownActionPerformed
        choiceTrack();
    }//GEN-LAST:event_programDropDownActionPerformed

    private void uniDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniDropDownActionPerformed
        choiceTrack();
    }//GEN-LAST:event_uniDropDownActionPerformed

    private void AddFirstClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFirstClassButtonActionPerformed
        ManualAddSpecifics screen = new ManualAddSpecifics();
        screen.setVisible(true);
        screen.toFront();
        dispose();
    }//GEN-LAST:event_AddFirstClassButtonActionPerformed

    private void courses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses1ActionPerformed
        chosenCourses.remove(courses1);
        chosenCourses.put(courses1, (String)courses1.getSelectedItem());
//        choicesNum++;
//        if(choicesNum >= 6){
//            isSelectionMade = true;
//            nextButton.setEnabled(true);
//        }
    }//GEN-LAST:event_courses1ActionPerformed

    private void courses2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses2ActionPerformed
        chosenCourses.remove(courses2);
        chosenCourses.put(courses2, (String)courses2.getSelectedItem());
//        choicesNum++;
//        if(choicesNum >= 6){
//            isSelectionMade = true;
//            nextButton.setEnabled(true);
//        }
    }//GEN-LAST:event_courses2ActionPerformed

    private void courses3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses3ActionPerformed
        chosenCourses.remove(courses3);
        chosenCourses.put(courses3, (String)courses3.getSelectedItem());
//        choicesNum++;
//        if(choicesNum >= 6){
//            isSelectionMade = true;
//            nextButton.setEnabled(true);
//        }
    }//GEN-LAST:event_courses3ActionPerformed

    private void courses4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses4ActionPerformed
        chosenCourses.remove(courses4);
        chosenCourses.put(courses4, (String)courses4.getSelectedItem());
//        choicesNum++;
//        if(choicesNum >= 6){
//            isSelectionMade = true;
//            nextButton.setEnabled(true);
//        }
    }//GEN-LAST:event_courses4ActionPerformed

    private void courses5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses5ActionPerformed
        chosenCourses.remove(courses5);
        chosenCourses.put(courses5, (String)courses5.getSelectedItem());
//        choicesNum++;
//        if(choicesNum >= 6){
//            isSelectionMade = true;
//            nextButton.setEnabled(true);
//        }
    }//GEN-LAST:event_courses5ActionPerformed

    private void courses6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses6ActionPerformed
        chosenCourses.remove(courses6);
        chosenCourses.put(courses6, (String)courses6.getSelectedItem());
//        choicesNum++;
//        if(choicesNum >= 6){
//            isSelectionMade = true;
//            nextButton.setEnabled(true);
//        }
    }//GEN-LAST:event_courses6ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClassScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFirstClassButton;
    private javax.swing.JComboBox<String> courses1;
    private javax.swing.JComboBox<String> courses2;
    private javax.swing.JComboBox<String> courses3;
    private javax.swing.JComboBox<String> courses4;
    private javax.swing.JComboBox<String> courses5;
    private javax.swing.JComboBox<String> courses6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox<String> programDropDown;
    private javax.swing.JComboBox<String> uniDropDown;
    // End of variables declaration//GEN-END:variables
}
