/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Yahya
 */
public class ManualAddSpecifics extends javax.swing.JFrame {
    
    private ArrayList<String> codes = new ArrayList<>();
    private ArrayList<Double> percents = new ArrayList<>();
    private ArrayList<Integer> weights = new ArrayList<>();
    private HashMap<String, String> course_Avg = new HashMap<>();
    private User user;
    private double perweightSum = 0;
    private int weightSum = 0;
    private double grade;
    private String courseName = null;
    private String oldCourse = null;
    private int index;
    
    private int addCount = 0;
    
    private double thisAvg = 0.00;
    private int totalWeight = 0;
    
    
    private int added = 0;
    
    public void printResults(){
        getCodeLabel().setText(getCodeLabel().getText() + "\n" + getCodeField().getText());
        getPercentLabel().setText(getPercentLabel().getText() + "\n" + getPercentField().getText());
        getWeightLabel().setText(getWeightLabel().getText() + "\n" + getWeightField().getText());
    }

    public ManualAddSpecifics(User u, int b) {
       user=u;
       index=b;
       initComponents();
       thisAvg = 0;
       totalWeight = 0;
       codes.clear();
       percents.clear();
       weights.clear();
       maxMSG.setVisible(false);
       CourseCodeDropDown.removeAllItems();
       for (String i : user.getAvailableCourses()){
           CourseCodeDropDown.addItem(i);
       }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CourseCode = new javax.swing.JLabel();
        CourseCodeDropDown = new javax.swing.JComboBox<>();
        CourseCode1 = new javax.swing.JLabel();
        currentAverageInput = new javax.swing.JTextField();
        CourseCode2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CodeField = new javax.swing.JTextField();
        PercentField = new javax.swing.JTextField();
        WeightField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        percentSignLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JTextPane();
        codeLabel = new javax.swing.JTextPane();
        percentLabel = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        CAinfo = new javax.swing.JButton();
        maxMSG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 128));

        CourseCode.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CourseCode.setForeground(new java.awt.Color(255, 255, 255));
        CourseCode.setText("Course Code:");

        CourseCodeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        CourseCodeDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseCodeDropDownActionPerformed(evt);
            }
        });

        CourseCode1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CourseCode1.setForeground(new java.awt.Color(255, 255, 255));
        CourseCode1.setText("Current Average (Optional):");

        currentAverageInput.setText("Enter Average");
        currentAverageInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentAverageInputMouseClicked(evt);
            }
        });
        currentAverageInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentAverageInputActionPerformed(evt);
            }
        });

        CourseCode2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CourseCode2.setForeground(new java.awt.Color(255, 255, 255));
        CourseCode2.setText("Add Grades:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Percentage");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight");

        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        percentSignLabel.setForeground(new java.awt.Color(255, 255, 255));
        percentSignLabel.setText("%");

        weightLabel.setBackground(new java.awt.Color(0, 5, 128));
        weightLabel.setBorder(null);
        weightLabel.setForeground(new java.awt.Color(255, 255, 255));
        weightLabel.setSelectedTextColor(new java.awt.Color(0, 0, 128));

        codeLabel.setBackground(new java.awt.Color(0, 0, 128));
        codeLabel.setBorder(null);
        codeLabel.setForeground(new java.awt.Color(255, 255, 255));

        percentLabel.setBackground(new java.awt.Color(0, 0, 128));
        percentLabel.setBorder(null);
        percentLabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input the values and press add:");

        CAinfo.setText("?");
        CAinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAinfoActionPerformed(evt);
            }
        });

        maxMSG.setForeground(new java.awt.Color(255, 51, 51));
        maxMSG.setText("Maximum number of assignments added.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maxMSG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PercentField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(percentSignLabel))
                                    .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(184, 184, 184)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(WeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)
                                        .addGap(81, 81, 81)
                                        .addComponent(AddButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(weightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CourseCode)
                                        .addGap(18, 18, 18)
                                        .addComponent(CourseCodeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CourseCode2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CourseCode1)
                                        .addGap(12, 12, 12)
                                        .addComponent(currentAverageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CAinfo)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CourseCode)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CourseCodeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CourseCode1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentAverageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAinfo))))
                .addGap(17, 17, 17)
                .addComponent(CourseCode2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(percentLabel)
                    .addComponent(weightLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PercentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(percentSignLabel))
                    .addComponent(WeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nextButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maxMSG)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CourseCodeDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseCodeDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseCodeDropDownActionPerformed

    private void currentAverageInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentAverageInputActionPerformed
        
    }//GEN-LAST:event_currentAverageInputActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if (getAddCount() < 100){
            try{
                getPercents().add(parseDouble(getPercentField().getText()));
                getWeights().add(parseInt(getWeightField().getText()));
                getCodes().add(getCodeField().getText());
            } catch (NumberFormatException e){
                System.out.println("Error.");
            }
            printResults();
            setAddCount(getAddCount() + 1);
            setThisAvg(getThisAvg() + Double.parseDouble(getPercentField().getText()) * Integer.parseInt(getWeightField().getText()));
            setTotalWeight(getTotalWeight() + Integer.parseInt(getWeightField().getText()));
            getCodeField().setText("");
            getPercentField().setText("");
            getWeightField().setText("");
        } else {
            getAddButton().setEnabled(false);
            getMaxMSG().setVisible(true);
        }       
    }//GEN-LAST:event_AddButtonActionPerformed

    private void currentAverageInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentAverageInputMouseClicked
        getCurrentAverageInput().setText("");
    }//GEN-LAST:event_currentAverageInputMouseClicked

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        if (getCourseCodeDropDown().getSelectedItem().equals("Select Course")){
            getNextButton().setText("Please Choose a Course");
        }
        else {
            if (!user.getCourses().get(index).equals("Add Class")){
                user.getAvailableCourses().remove(String.valueOf(getCourseCodeDropDown().getSelectedItem()));
                user.replaceCourse(index, new UniCourse(user, String.valueOf(getCourseCodeDropDown().getSelectedItem())));
            }
            else{
                user.getAvailableCourses().add(user.getCourses().get(index).getName());
                user.getAvailableCourses().remove(String.valueOf(getCourseCodeDropDown().getSelectedItem()));
                user.replaceCourse(index, new UniCourse(user, String.valueOf(getCourseCodeDropDown().getSelectedItem())));
            }
            
            for(int x=0;x<=getCodes().size()-1;x++ ){
                user.getCourses().get(index).addAssignment(new UniAssignment(getCodes().get(x), getPercents().get(x), getWeights().get(x)));
            }
            AddClassScreen screen = new AddClassScreen(user);
            screen.setVisible(true);
            screen.toFront();
            dispose();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void CAinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAinfoActionPerformed
        JOptionPane.showMessageDialog(this.getCAinfo(), "Writing in this box is optional. This overrides the calculation the app does to calculate the\naverage in case you grade has been changed and the grades do not reflect it.");
    }//GEN-LAST:event_CAinfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CAinfo;
    private javax.swing.JTextField CodeField;
    private javax.swing.JLabel CourseCode;
    private javax.swing.JLabel CourseCode1;
    private javax.swing.JLabel CourseCode2;
    public static javax.swing.JComboBox<String> CourseCodeDropDown;
    private javax.swing.JTextField PercentField;
    private javax.swing.JTextField WeightField;
    private javax.swing.JTextPane codeLabel;
    private javax.swing.JTextField currentAverageInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maxMSG;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextPane percentLabel;
    private javax.swing.JLabel percentSignLabel;
    private javax.swing.JTextPane weightLabel;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the codes
     */
    public ArrayList<String> getCodes() {
        return codes;
    }

    /**
     * @param codes the codes to set
     */
    public void setCodes(ArrayList<String> codes) {
        this.codes = codes;
    }

    /**
     * @return the percents
     */
    public ArrayList<Double> getPercents() {
        return percents;
    }

    /**
     * @param percents the percents to set
     */
    public void setPercents(ArrayList<Double> percents) {
        this.percents = percents;
    }

    /**
     * @return the weights
     */
    public ArrayList<Integer> getWeights() {
        return weights;
    }

    /**
     * @param weights the weights to set
     */
    public void setWeights(ArrayList<Integer> weights) {
        this.weights = weights;
    }

    /**
     * @return the course_Avg
     */
    public HashMap<String, String> getCourse_Avg() {
        return course_Avg;
    }

    /**
     * @param course_Avg the course_Avg to set
     */
    public void setCourse_Avg(HashMap<String, String> course_Avg) {
        this.course_Avg = course_Avg;
    }

    /**
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return the perweightSum
     */
    public double getPerweightSum() {
        return perweightSum;
    }

    /**
     * @param perweightSum the perweightSum to set
     */
    public void setPerweightSum(double perweightSum) {
        this.perweightSum = perweightSum;
    }

    /**
     * @return the weightSum
     */
    public int getWeightSum() {
        return weightSum;
    }

    /**
     * @param weightSum the weightSum to set
     */
    public void setWeightSum(int weightSum) {
        this.weightSum = weightSum;
    }

    /**
     * @return the grade
     */
    public double getGrade() {
        return grade;
    }

    /**
     * @param grade the grade to set
     */
    public void setGrade(double grade) {
        this.grade = grade;
    }

    /**
     * @return the courseName
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * @param courseName the courseName to set
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * @return the oldCourse
     */
    public String getOldCourse() {
        return oldCourse;
    }

    /**
     * @param oldCourse the oldCourse to set
     */
    public void setOldCourse(String oldCourse) {
        this.oldCourse = oldCourse;
    }

    /**
     * @return the addCount
     */
    public int getAddCount() {
        return addCount;
    }

    /**
     * @param addCount the addCount to set
     */
    public void setAddCount(int addCount) {
        this.addCount = addCount;
    }

    /**
     * @return the thisAvg
     */
    public double getThisAvg() {
        return thisAvg;
    }

    /**
     * @param thisAvg the thisAvg to set
     */
    public void setThisAvg(double thisAvg) {
        this.thisAvg = thisAvg;
    }

    /**
     * @return the totalWeight
     */
    public int getTotalWeight() {
        return totalWeight;
    }

    /**
     * @param totalWeight the totalWeight to set
     */
    public void setTotalWeight(int totalWeight) {
        this.totalWeight = totalWeight;
    }

    /**
     * @return the added
     */
    public int getAdded() {
        return added;
    }

    /**
     * @param added the added to set
     */
    public void setAdded(int added) {
        this.added = added;
    }

    /**
     * @return the AddButton
     */
    public javax.swing.JButton getAddButton() {
        return AddButton;
    }

    /**
     * @param AddButton the AddButton to set
     */
    public void setAddButton(javax.swing.JButton AddButton) {
        this.AddButton = AddButton;
    }

    /**
     * @return the CAinfo
     */
    public javax.swing.JButton getCAinfo() {
        return CAinfo;
    }

    /**
     * @param CAinfo the CAinfo to set
     */
    public void setCAinfo(javax.swing.JButton CAinfo) {
        this.CAinfo = CAinfo;
    }

    /**
     * @return the CodeField
     */
    public javax.swing.JTextField getCodeField() {
        return CodeField;
    }

    /**
     * @param CodeField the CodeField to set
     */
    public void setCodeField(javax.swing.JTextField CodeField) {
        this.CodeField = CodeField;
    }

    /**
     * @return the CourseCode
     */
    public javax.swing.JLabel getCourseCode() {
        return CourseCode;
    }

    /**
     * @param CourseCode the CourseCode to set
     */
    public void setCourseCode(javax.swing.JLabel CourseCode) {
        this.CourseCode = CourseCode;
    }

    /**
     * @return the CourseCode1
     */
    public javax.swing.JLabel getCourseCode1() {
        return CourseCode1;
    }

    /**
     * @param CourseCode1 the CourseCode1 to set
     */
    public void setCourseCode1(javax.swing.JLabel CourseCode1) {
        this.CourseCode1 = CourseCode1;
    }

    /**
     * @return the CourseCode2
     */
    public javax.swing.JLabel getCourseCode2() {
        return CourseCode2;
    }

    /**
     * @param CourseCode2 the CourseCode2 to set
     */
    public void setCourseCode2(javax.swing.JLabel CourseCode2) {
        this.CourseCode2 = CourseCode2;
    }

    /**
     * @return the CourseCodeDropDown
     */
    public static javax.swing.JComboBox<String> getCourseCodeDropDown() {
        return CourseCodeDropDown;
    }

    /**
     * @param aCourseCodeDropDown the CourseCodeDropDown to set
     */
    public static void setCourseCodeDropDown(javax.swing.JComboBox<String> aCourseCodeDropDown) {
        CourseCodeDropDown = aCourseCodeDropDown;
    }

    /**
     * @return the PercentField
     */
    public javax.swing.JTextField getPercentField() {
        return PercentField;
    }

    /**
     * @param PercentField the PercentField to set
     */
    public void setPercentField(javax.swing.JTextField PercentField) {
        this.PercentField = PercentField;
    }

    /**
     * @return the WeightField
     */
    public javax.swing.JTextField getWeightField() {
        return WeightField;
    }

    /**
     * @param WeightField the WeightField to set
     */
    public void setWeightField(javax.swing.JTextField WeightField) {
        this.WeightField = WeightField;
    }

    /**
     * @return the codeLabel
     */
    public javax.swing.JTextPane getCodeLabel() {
        return codeLabel;
    }

    /**
     * @param codeLabel the codeLabel to set
     */
    public void setCodeLabel(javax.swing.JTextPane codeLabel) {
        this.codeLabel = codeLabel;
    }

    /**
     * @return the currentAverageInput
     */
    public javax.swing.JTextField getCurrentAverageInput() {
        return currentAverageInput;
    }

    /**
     * @param currentAverageInput the currentAverageInput to set
     */
    public void setCurrentAverageInput(javax.swing.JTextField currentAverageInput) {
        this.currentAverageInput = currentAverageInput;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the maxMSG
     */
    public javax.swing.JLabel getMaxMSG() {
        return maxMSG;
    }

    /**
     * @param maxMSG the maxMSG to set
     */
    public void setMaxMSG(javax.swing.JLabel maxMSG) {
        this.maxMSG = maxMSG;
    }

    /**
     * @return the nextButton
     */
    public javax.swing.JButton getNextButton() {
        return nextButton;
    }

    /**
     * @param nextButton the nextButton to set
     */
    public void setNextButton(javax.swing.JButton nextButton) {
        this.nextButton = nextButton;
    }

    /**
     * @return the percentLabel
     */
    public javax.swing.JTextPane getPercentLabel() {
        return percentLabel;
    }

    /**
     * @param percentLabel the percentLabel to set
     */
    public void setPercentLabel(javax.swing.JTextPane percentLabel) {
        this.percentLabel = percentLabel;
    }

    /**
     * @return the percentSignLabel
     */
    public javax.swing.JLabel getPercentSignLabel() {
        return percentSignLabel;
    }

    /**
     * @param percentSignLabel the percentSignLabel to set
     */
    public void setPercentSignLabel(javax.swing.JLabel percentSignLabel) {
        this.percentSignLabel = percentSignLabel;
    }

    /**
     * @return the weightLabel
     */
    public javax.swing.JTextPane getWeightLabel() {
        return weightLabel;
    }

    /**
     * @param weightLabel the weightLabel to set
     */
    public void setWeightLabel(javax.swing.JTextPane weightLabel) {
        this.weightLabel = weightLabel;
    }
}
