
import java.io.IOException;
import java.util.*;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLayeredPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yahya
 */
public class SettingsScreen extends javax.swing.JFrame {
    
    public static double currentAvg = 90.56;
    public double currentGoal;
    public static int centerButtonColour = 0;

    /**
     * Creates new form SettingsScreen
     */
    public SettingsScreen() {
        initComponents();
        remove(jPanel1);
        remove(jPanel2);
        JLayeredPane layers = new JLayeredPane();
        jPanel2.setOpaque(false);
        layers.add(jPanel1, JLayeredPane.PALETTE_LAYER);
        layers.add(jPanel2, JLayeredPane.DEFAULT_LAYER);
        uniInfo.putty();
        for (String i: uniInfo.universities){
            uniDropDown.addItem(i);
        }
        for (String i: uniInfo.ottawa){
            programDropDown.addItem(i);
        }
    }
    
    public void dropDownActPer(){
        switch (String.valueOf(uniDropDown.getSelectedItem())){
            case "uOttawa":
                switch (String.valueOf(programDropDown.getSelectedItem())){
                    case uniInfo.PROG_NAME_01:
                        tempGradeText.setText(String.valueOf(uniInfo.ottGrades[0]));
                        currentGoal = uniInfo.ottGrades[0];
                        break;
                    case uniInfo.PROG_NAME_02:
                        tempGradeText.setText(String.valueOf(uniInfo.ottGrades[1]));
                        currentGoal = uniInfo.ottGrades[1];
                        break;
                    case uniInfo.PROG_NAME_03:
                        tempGradeText.setText(String.valueOf(uniInfo.ottGrades[2]));
                        currentGoal = uniInfo.ottGrades[2];
                        break;
                    default:
                        System.out.println("Error.");
                    }
                    break;
            case "uToronto":
                switch (String.valueOf(programDropDown.getSelectedItem())){
                    case "Computer Science":
                        tempGradeText.setText(String.valueOf(uniInfo.torGrades[0]));
                        currentGoal = uniInfo.torGrades[0];
                        break;
                    case "Biology":
                        tempGradeText.setText(String.valueOf(uniInfo.torGrades[1]));
                        currentGoal = uniInfo.torGrades[1];
                        break;
                    case "Life Sciences":
                        tempGradeText.setText(String.valueOf(uniInfo.torGrades[2]));
                        currentGoal = uniInfo.torGrades[2];
                        break;
                    default:
                        System.out.println("Error.");
                    }
                    break;
        }
        if (currentAvg == currentGoal || ((currentAvg > (currentGoal - 2)) && (currentAvg < (currentGoal + 2)))){
            gradeRecBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/requiredAVGyellow.png/")));
            centerButtonColour = 0;
        } else if (currentAvg < (currentGoal - 2)){
            gradeRecBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/requiredAVGred.png/")));
            centerButtonColour = 1;
        } else if (currentAvg > (currentGoal + 2)){
            gradeRecBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/requiredAVGgreen.png/")));
            centerButtonColour = 2;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        programDropDown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        uniDropDown = new javax.swing.JComboBox<>();
        gradeRecBG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uoinfoButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tempGradeText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 128));
        jPanel1.setMaximumSize(new java.awt.Dimension(226, 76));
        jPanel1.setMinimumSize(new java.awt.Dimension(226, 76));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backButton.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Program: ");

        programDropDown.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                programDropDownMouseMoved(evt);
            }
        });
        programDropDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                programDropDownMouseClicked(evt);
            }
        });
        programDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programDropDownActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My University: ");

        uniDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniDropDownActionPerformed(evt);
            }
        });

        gradeRecBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/requiredAVGred.png"))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("This is the estimated required average of your top 6 high school classes to be admitted into this program:");

        uoinfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uoinfoLOGO2.png"))); // NOI18N
        uoinfoButton.setBorder(null);
        uoinfoButton.setBorderPainted(false);
        uoinfoButton.setContentAreaFilled(false);
        uoinfoButton.setMaximumSize(new java.awt.Dimension(100, 50));
        uoinfoButton.setMinimumSize(new java.awt.Dimension(100, 50));
        uoinfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uoinfoButtonActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Open program in:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(uniDropDown, 0, 164, Short.MAX_VALUE)
                                            .addComponent(programDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(gradeRecBG))))
                        .addGap(0, 166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uoinfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(programDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uniDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(gradeRecBG)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(uoinfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        tempGradeText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tempGradeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tempGradeText.setText("GRADE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(tempGradeText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(tempGradeText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(538, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(332, 332, 332)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(801, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainScreen screen = new MainScreen();
        screen.setVisible(true);
        screen.toFront();
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void programDropDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programDropDownMouseClicked

    }//GEN-LAST:event_programDropDownMouseClicked

    private void programDropDownMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programDropDownMouseMoved

    }//GEN-LAST:event_programDropDownMouseMoved

    private void programDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programDropDownActionPerformed
        dropDownActPer();
    }//GEN-LAST:event_programDropDownActionPerformed

    private void uniDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniDropDownActionPerformed
        dropDownActPer();
    }//GEN-LAST:event_uniDropDownActionPerformed

    private void uoinfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uoinfoButtonActionPerformed
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("https://www.ouinfo.ca/"));
        } catch (IOException ex) {
            Logger.getLogger(SettingsScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uoinfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel gradeRecBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> programDropDown;
    private javax.swing.JLabel tempGradeText;
    private javax.swing.JComboBox<String> uniDropDown;
    private javax.swing.JButton uoinfoButton;
    // End of variables declaration//GEN-END:variables
}
