/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.hangman;
import java.util.*;

import java.awt.Color;



/**
 *
 * @author hatam1
 */
public class Main extends javax.swing.JFrame {
    int letterCount = 0;
    String word = "HELLO";
    List<String> lettersXYZ = new ArrayList<>();
    /**
     * Creates new form mainHangmanUI
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Hbutton = new javax.swing.JButton();
        Rbutton = new javax.swing.JButton();
        Ebutton = new javax.swing.JButton();
        Gbutton = new javax.swing.JButton();
        Fbutton = new javax.swing.JButton();
        Lbutton = new javax.swing.JButton();
        Bbutton = new javax.swing.JButton();
        Nbutton = new javax.swing.JButton();
        Pbutton = new javax.swing.JButton();
        Obutton = new javax.swing.JButton();
        Xbutton = new javax.swing.JButton();
        Dbutton = new javax.swing.JButton();
        Tbutton = new javax.swing.JButton();
        Mbutton = new javax.swing.JButton();
        Qbutton = new javax.swing.JButton();
        Sbutton = new javax.swing.JButton();
        Vbutton = new javax.swing.JButton();
        Jbutton = new javax.swing.JButton();
        Wbutton = new javax.swing.JButton();
        Abutton = new javax.swing.JButton();
        Cbutton = new javax.swing.JButton();
        Kbutton = new javax.swing.JButton();
        Ibutton = new javax.swing.JButton();
        Zbutton = new javax.swing.JButton();
        Ybutton = new javax.swing.JButton();
        Ubutton = new javax.swing.JButton();
        LetterOne = new javax.swing.JTextField();
        LetterTwo = new javax.swing.JTextField();
        LetterThree = new javax.swing.JTextField();
        LetterFour = new javax.swing.JTextField();
        LetterFive = new javax.swing.JTextField();
        LetterSix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jPanel2.setPreferredSize(new java.awt.Dimension(410, 90));

        Hbutton.setText("H");
        Hbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbuttonActionPerformed(evt);
            }
        });

        Rbutton.setText("R");
        Rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbuttonActionPerformed(evt);
            }
        });

        Ebutton.setText("E");
        Ebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EbuttonActionPerformed(evt);
            }
        });

        Gbutton.setText("G");
        Gbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbuttonActionPerformed(evt);
            }
        });

        Fbutton.setText("F");
        Fbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FbuttonActionPerformed(evt);
            }
        });

        Lbutton.setText("L");
        Lbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbuttonActionPerformed(evt);
            }
        });

        Bbutton.setText("B");
        Bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuttonActionPerformed(evt);
            }
        });

        Nbutton.setText("N");
        Nbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbuttonActionPerformed(evt);
            }
        });

        Pbutton.setText("P");
        Pbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbuttonActionPerformed(evt);
            }
        });

        Obutton.setText("O");
        Obutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObuttonActionPerformed(evt);
            }
        });

        Xbutton.setText("X");
        Xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XbuttonActionPerformed(evt);
            }
        });

        Dbutton.setText("D");
        Dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbuttonActionPerformed(evt);
            }
        });

        Tbutton.setText("T");
        Tbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbuttonActionPerformed(evt);
            }
        });

        Mbutton.setText("M");
        Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbuttonActionPerformed(evt);
            }
        });

        Qbutton.setText("Q");
        Qbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QbuttonActionPerformed(evt);
            }
        });

        Sbutton.setText("S");
        Sbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbuttonActionPerformed(evt);
            }
        });

        Vbutton.setText("V");
        Vbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VbuttonActionPerformed(evt);
            }
        });

        Jbutton.setText("J");
        Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonActionPerformed(evt);
            }
        });

        Wbutton.setText("W");
        Wbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WbuttonActionPerformed(evt);
            }
        });

        Abutton.setText("A");
        Abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbuttonActionPerformed(evt);
            }
        });

        Cbutton.setText("C");
        Cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbuttonActionPerformed(evt);
            }
        });

        Kbutton.setText("K");
        Kbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbuttonActionPerformed(evt);
            }
        });

        Ibutton.setText("I");
        Ibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbuttonActionPerformed(evt);
            }
        });

        Zbutton.setText("Z");
        Zbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZbuttonActionPerformed(evt);
            }
        });

        Ybutton.setText("Y");
        Ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YbuttonActionPerformed(evt);
            }
        });

        Ubutton.setText("U");
        Ubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Obutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Qbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rbutton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Abutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ibutton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Sbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ubutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Xbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ybutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zbutton)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Abutton, Bbutton, Cbutton, Dbutton, Ebutton, Fbutton, Gbutton, Hbutton, Ibutton, Jbutton, Kbutton, Lbutton, Mbutton, Nbutton, Obutton, Pbutton, Qbutton, Rbutton, Sbutton, Tbutton, Ubutton, Vbutton, Wbutton, Xbutton, Ybutton, Zbutton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Abutton)
                    .addComponent(Bbutton)
                    .addComponent(Cbutton)
                    .addComponent(Dbutton)
                    .addComponent(Ebutton)
                    .addComponent(Fbutton)
                    .addComponent(Gbutton)
                    .addComponent(Hbutton)
                    .addComponent(Ibutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbutton)
                    .addComponent(Kbutton)
                    .addComponent(Lbutton)
                    .addComponent(Mbutton)
                    .addComponent(Nbutton)
                    .addComponent(Obutton)
                    .addComponent(Pbutton)
                    .addComponent(Qbutton)
                    .addComponent(Rbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sbutton)
                    .addComponent(Tbutton)
                    .addComponent(Ubutton)
                    .addComponent(Vbutton)
                    .addComponent(Wbutton)
                    .addComponent(Xbutton)
                    .addComponent(Ybutton)
                    .addComponent(Zbutton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Abutton, Bbutton, Cbutton, Dbutton, Ebutton, Fbutton, Gbutton, Hbutton, Ibutton, Jbutton, Kbutton, Lbutton, Mbutton, Nbutton, Obutton, Pbutton, Qbutton, Rbutton, Sbutton, Tbutton, Ubutton, Vbutton, Wbutton, Xbutton, Ybutton, Zbutton});

        LetterOne.setToolTipText("");
        LetterOne.setMaximumSize(new java.awt.Dimension(22, 22));
        LetterOne.setMinimumSize(new java.awt.Dimension(22, 22));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(LetterOne, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterThree, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterFour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterFive, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LetterSix, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetterTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetterThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetterFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetterFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetterSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbuttonActionPerformed

    private void YbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YbuttonActionPerformed

    private void ZbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZbuttonActionPerformed

    private void IbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IbuttonActionPerformed

    private void KbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KbuttonActionPerformed

    private void CbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbuttonActionPerformed

    private void AbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbuttonActionPerformed
        if (word.contains("A")){
            Abutton.setBackground(Color.green);
        } else {
            Abutton.setBackground(Color.red);
        }
    }//GEN-LAST:event_AbuttonActionPerformed

    private void WbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WbuttonActionPerformed

    private void JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbuttonActionPerformed

    private void VbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VbuttonActionPerformed

    private void SbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SbuttonActionPerformed

    private void QbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QbuttonActionPerformed

    private void MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MbuttonActionPerformed

    private void TbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbuttonActionPerformed

    private void DbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DbuttonActionPerformed

    private void XbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XbuttonActionPerformed

    private void ObuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObuttonActionPerformed
        if (word.contains("O")){
            Obutton.setBackground(Color.green);
            System.out.print(word.indexOf("O"));
        } else {
            Obutton.setBackground(Color.red);
        }
    }//GEN-LAST:event_ObuttonActionPerformed

    private void PbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PbuttonActionPerformed

    private void NbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NbuttonActionPerformed

    private void BbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BbuttonActionPerformed

    private void LbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LbuttonActionPerformed

    private void FbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FbuttonActionPerformed

    private void GbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GbuttonActionPerformed

    private void EbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EbuttonActionPerformed

    private void RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbuttonActionPerformed

    private void HbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abutton;
    private javax.swing.JButton Bbutton;
    private javax.swing.JButton Cbutton;
    private javax.swing.JButton Dbutton;
    private javax.swing.JButton Ebutton;
    private javax.swing.JButton Fbutton;
    private javax.swing.JButton Gbutton;
    private javax.swing.JButton Hbutton;
    private javax.swing.JButton Ibutton;
    private javax.swing.JButton Jbutton;
    private javax.swing.JButton Kbutton;
    private javax.swing.JButton Lbutton;
    private javax.swing.JTextField LetterFive;
    private javax.swing.JTextField LetterFour;
    private javax.swing.JTextField LetterOne;
    private javax.swing.JTextField LetterSix;
    private javax.swing.JTextField LetterThree;
    private javax.swing.JTextField LetterTwo;
    private javax.swing.JButton Mbutton;
    private javax.swing.JButton Nbutton;
    private javax.swing.JButton Obutton;
    private javax.swing.JButton Pbutton;
    private javax.swing.JButton Qbutton;
    private javax.swing.JButton Rbutton;
    private javax.swing.JButton Sbutton;
    private javax.swing.JButton Tbutton;
    private javax.swing.JButton Ubutton;
    private javax.swing.JButton Vbutton;
    private javax.swing.JButton Wbutton;
    private javax.swing.JButton Xbutton;
    private javax.swing.JButton Ybutton;
    private javax.swing.JButton Zbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
